<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE collection [
<!ELEMENT Navyki (Frontehnd,Dizajn,Behkehnd,Vspomogatelnye_instrumenty)>
<!ATTLIST Navyki
  xmlns CDATA #FIXED ''>
<!ELEMENT Frontehnd (stepen_osvedomlennosti,CSS,JavaScript)>
<!ATTLIST Frontehnd
  xmlns CDATA #FIXED ''>
<!ELEMENT Dizajn (stepen_osvedomlennosti)+>
<!ATTLIST Dizajn
  xmlns CDATA #FIXED ''>
<!ELEMENT Behkehnd (Bazy_dannyh,YAzyki)>
<!ATTLIST Behkehnd
  xmlns CDATA #FIXED ''>
<!ELEMENT Vspomogatelnye_instrumenty (stepen_osvedomlennosti)+>
<!ATTLIST Vspomogatelnye_instrumenty
  xmlns CDATA #FIXED ''>
<!ELEMENT CSS (stepen_osvedomlennosti)>
<!ATTLIST CSS
  xmlns CDATA #FIXED ''
  znachenie NMTOKEN #REQUIRED>
<!ELEMENT JavaScript (stepen_osvedomlennosti)+>
<!ATTLIST JavaScript
  xmlns CDATA #FIXED ''
  znachenie NMTOKEN #REQUIRED>
<!ELEMENT Bazy_dannyh (stepen_osvedomlennosti)>
<!ATTLIST Bazy_dannyh
  xmlns CDATA #FIXED ''>
<!ELEMENT YAzyki (stepen_osvedomlennosti)>
<!ATTLIST YAzyki
  xmlns CDATA #FIXED ''>
<!ELEMENT stepen_osvedomlennosti EMPTY>
<!ATTLIST stepen_osvedomlennosti
  xmlns CDATA #FIXED ''
  v NMTOKEN #REQUIRED
  znachenie CDATA #REQUIRED>
]>
<Navyki>
    <Frontehnd>
        <stepen_osvedomlennosti v="HTML" znachenie="koe-chto umeyu" />
        <CSS znachenie="srednen'ko">
            <stepen_osvedomlennosti v="Bootstrap" znachenie="uspeshno izmenyayu chuzhie shablony" />
        </CSS>
        <JavaScript znachenie="chajnik">
            <stepen_osvedomlennosti v="jQuery" znachenie="umeyu obrashchat'sya k ehlementam" />
            <stepen_osvedomlennosti v="AJAX" znachenie="malo chto umeyu, no znayu chto takoe" />
        </JavaScript>
    </Frontehnd>
    <Dizajn>
        <stepen_osvedomlennosti v="Photoshop" znachenie="na chetverochku" />
        <stepen_osvedomlennosti v="CorelDRAW" znachenie="na troechku" />
    </Dizajn>
    <Behkehnd>
        <Bazy_dannyh>
            <stepen_osvedomlennosti v="MySQL" znachenie="napishu zapros, no ne po trem tablicam" />
        </Bazy_dannyh>
        <YAzyki>
            <stepen_osvedomlennosti v="PHP" znachenie="udovletvoritelno" />
        </YAzyki>
    </Behkehnd>
    <Vspomogatelnye_instrumenty>
        <stepen_osvedomlennosti v="Git" znachenie="smogu zakinut' sajt v repozitorij" />
        <stepen_osvedomlennosti v="Trello" znachenie="i poluchit' novuyu zadachu" />
    </Vspomogatelnye_instrumenty>
</Navyki>

